### ISSUE TITLE
panda fails to compile on Ubuntu 16.04, 64 bit

### ISSUE THREAD

**Issue by HolmesSherlock** [panda-re/panda#408]
With `llvm-3.3` and `clang-3.3`, the following error is thrown on `Ubuntu 16.04, 64 bit`.

```
/data/programs/panda/target/i386/cpu.h:1018:5: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]                                                                                      
    struct {} start_init_save;                                                                                                                                                                                     
    ^                                                                                                                                                                                                              
/data/programs/panda/target/i386/cpu.h:1084:5: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]                                                                                      
    struct {} end_init_save;                                                                                                                                                                                       
    ^                                                                                                                                                                                                              
/data/programs/panda/target/i386/cpu.h:1132:5: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]                                                                                      
    struct {} end_reset_fields;                                                                                                                                                                                    
    ^                                                                                                                                                                                                              
In file included from /data/programs/panda/panda/plugins/taint2/taint_ops.cpp:38:
In file included from /data/programs/panda/panda/include/panda/plugin.h:18:
In file included from /data/programs/panda/panda/include/panda/cheaders.h:24:
/data/programs/panda/target/arm/cpu.h:506:5: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]                                                                                       
    struct {} end_reset_fields;
    ^
In file included from /data/programs/panda/panda/plugins/taint2/taint_ops.cpp:38:
In file included from /data/programs/panda/panda/include/panda/plugin.h:18:
In file included from /data/programs/panda/panda/include/panda/cheaders.h:24:
/data/programs/panda/target/i386/cpu.h:1018:5: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]                                                                                     
    struct {} start_init_save;
    ^
/data/programs/panda/target/i386/cpu.h:1084:5: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]                                                                                     
    struct {} end_init_save;
    ^
/data/programs/panda/target/i386/cpu.h:1132:5: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]                                                                                     
    struct {} end_reset_fields;
    ^
.
.
.
/usr/lib/llvm-3.3/bin/llvm-link: panda/plugins/taint2/taint_ops_llvm.bc: error: Global not a pointer type!
/usr/lib/llvm-3.3/bin/llvm-link: error loading file 'panda/plugins/taint2/taint_ops_llvm.bc'
/data/programs/panda/panda/plugins/taint2/Makefile:36: recipe for target 'panda/plugins/panda_taint2_ops.bc' failed
make[2]: *** [panda/plugins/panda_taint2_ops.bc] Error 1
/data/programs/panda/panda/Makefile.panda.target:42: recipe for target 'plugin-taint2' failed
make[1]: *** [plugin-taint2] Error 2
```

**Comment by HolmesSherlock** [comment]
Turned out somehow `llvm-3.8/clang-3.8` was being picked up as the compiler while `llvm-link-3.3` as the linker. For future reference, turn on verbose logging by `V=1 ../build.sh` as suggested by @moyix [here](https://github.com/panda-re/lava/issues/18). You should be able to get to see the absolute paths to both the compiler and the linker.
